dct = {
    'Acceleration':{
        'units':{
            'g-force':'g-force',
            'm/s²':'metres per second squared' #(meters?)
        },
        'default':'m/s²',
    },
    'Angle':{
        'units':{
            'arcmin':'arcminutes',
            'arcsec':'arcseconds', 
            'deg':'degrees',
            'grad':'grad',
            'rad':'radians',
            'rev':'revolution',
        },
        'default':'deg',
    },
    'Area':{
        'units':{
            'a':'a',
            'acre':'acres',
            'cm²':'square centimetres',
            'ft²':'square feet',
            'hectare':'hectares',
            'in²':'square inches',
            'km²':'square kilometres',
            'm²':'square metres',  # actually displayed as 'metres²'
            'mi²':'square square miles',
            'ft²':'square feet',
            'Mm²':'Mm²',
            'mm²':'mm²',
            'nm²':'nm²',
            'square yards':'square yards',
            'μm²':'μm²',
        },
        'default':'m²',
    },
    'Concentration Mass':{
        'units':{
            'g/L':'g/L',
            'mg/dl':'milligrams per decilitre',
            'μg/m³':'μg/m³',
        },
        'default':'mg/dl',
    },
    'Dispersion':{
        'units':{
            'ppm':'parts per million',
        },
        'default':'ppm',
    },
    'Duration':{
        'units':{
            'hour':'hours',
            'min':'minutes',
            'msec':'milliseconds',
            'ns':'nanoseconds',
            'ps':'ps',
            'sec':'seconds',
            'μsec':'microseconds',
        },
        'default':'min',
    },
    'Electric Charge':{
        'units':{
            'Ah':'Ah',
            'C':'C',
            'kAh':'kAh',
            'mAh':'mAh',
            'MAh':'MAh',
            'μAh':'μAh',
        },
        'default':'Ah',
    },
    'Electric Current':{
        'units':{
            'amp':'amperes',
            'kA':'kA',
            'MA':'MA',
            'mA':'milliamperes',
            'μA':'μA',
        },
        'default':'amp',
    },
    'Electric Potential Difference':{
        'units':{
            'kV':'kV',
            'MV':'MV',
            'mV':'mV',
            'volt':'volts',
            'μV':'μV',
        },
        'default':'volt',
    },
    'Electric Resistance':{
        'units':{
            'kΩ':'kΩ',
            'MΩ':'MΩ',
            'mΩ':'mΩ',
            'μΩ':'μΩ',
            'ohm':'ohms',
        },
        'default':'ohm',
    },
    'Energy':{
        'units':{
            'cal':'calories',
            'joule':'joules',
            'kcal':'kilocalories',
            'kJ':'kilojoules',
            'kWh':'kilowatt-hours',
        },
        'default':'joule',
    },
    'Frequency':{
        'units':{
            'fps':'fps',
            'GHz':'gigahertz',
            'Hz':'hertz',
            'kHz':'kilohertz',
            'mHz':'mHz',
            'MHz':'megahertz',
            'nHz':'nHz',
            'THz':'THz',
            'μHz':'μHz',
        },
        'default':'Hz',
    },
    'Fuel Efficiency':{
        'units':{
            'l/100km':'litres per 100 kilometres',
            'mpg US':'miles per US gallon',
        },
        'default':'l/100km',
    },
    'Illuminance':{
        'units':{
            'lux':'lux',
        },
        'default':'lux',
    },
    'Information Storage':{
        'units':{
            'bytes':'bytes',
            'EB':'EB',
            'GB':'GB',
            'KB':'KB',
            'MB':'MB',
            'PB':'PB',
            'TB':'TB',
            'YB':'YB',
            'ZB':'ZB',
        },
        'default':'MB',
    },
    'Length':{
        'units':{
            'cm':'centimetres',
            'dam':'dam',
            'dm':'decimetre',
            'ft':'feet',
            'fathom':'fathoms',
            'furlong':'furlongs',
            'hm':'hm',
            'in':'inches',
            'km':'kilometres',
            'ly':'light years',
            'm':'metres',
            'mi':'miles',
            'mm':'millimetres',
            'Mm':'Mm',
            'nm':'nanometres',
            'nmi':'nautical miles',
            'parsec':'parsecs',
            'pm':'picometres',
            'smi':'mile-scandinavian',
            'au':'astronomical units',
            'yd':'yards',
            'μm':'micrometre',
        },
        'default':'m',
    },
    'Mass':{
        'units':{
            'cg':'cg',
            'carat':'carats',
            'dg':'dg',
            'gram':'grams',
            'kg':'kilograms',
            'lb':'pounds',
            'mg':'milligrams',
            'ng':'ng',
            'oz':'ounces',
            'oz t':'troy ounces',
            'pg':'pg',
            'slug':'slug',
            'stone':'stone',
            't':'tonne',
            'ton':'tons',
            'μg':'micrograms',
        },
        'default':'gram',
    },
    'Power':{
        'units':{
            'fW':'fW',
            'GW':'gigawatts',
            'hp':'horsepower',
            'kW':'kilowatts',
            'MW':'megawatts',
            'mW':'milliwatts',
            'nW':'nW',
            'pW':'pW',
            'TW':'TW',
            'watt':'watts',
            'μW':'μW',
        },
        'default':'watt',
    },
    'Pressure':{
        'units':{
            'bar':'bar',
            'GPa':'GPa',
            'hPa':'hectopascals',
            'inHg':'″Hg',  #'inches of mercury'
            'kPa':'kPa',
            'mbar':'millibars',
            'mmHg':'millimetres of mercury',
            'MPa':'MPa',
            'N/m²':'N/m²',
        },
        'default':'mbar',
    },
    'Speed':{
        'units':{
            'km/hr':'kilometres per hour',
            'kn':'knots',
            'm/s':'metres per second',
            'mi/hr':'miles per hour',
        },
        'default':'km/hr',
    },
    'Temperature':{
        'units':{
            '°C':'degrees Celsius',
            '°F':'degrees Fahrenheit',
            'K':'Kelvin',
        },
        'default':'',
    },
    'Volume':{
        'units':{
            'acre ft':'acre-feet',
            'bushel':'bushels',
            'cl':'centilitres',
            'cm³':'cubic centimetres',
            'cup':'cups',
            'dl':'decilitres',
            'dm³':'dm³',
            'fl oz':'fluid ounces',
            'ft³':'cubic feet',
            'gal':'gallons',
            'in³':'cubic inches',
            'kL':'kL',
            'km³':'cubic kilometres',
            'litre':'litres',
            'm³':'metres',
            'mcup':'metric cups',
            'mi³':'cubic miles',
            'ml':'millilitres',
            'Ml':'megalitres',
            'mm³':'mm³',
            'pt':'pints',
            'qt':'quarts',
            'tbsp':'tablespoons',
            'tsp':'teaspoons',
            'yd³':'cubic yards',
        },
        'default':'litre',
    },
}