# Generated by Django 2.2.6 on 2019-11-10 05:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('iCloud', models.URLField(help_text='iCloud link created by Sharing your Shortcut', max_length=100, verbose_name='iCloud link')),
                ('iCloudID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='iCloud ID')),
                ('download_link', models.URLField(verbose_name='Download Link')),
                ('Actions', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Shortcut Actions')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('glyphID', models.PositiveIntegerField(default=59771, verbose_name='Glyph ID')),
                ('colorID', models.PositiveIntegerField(default=431817727, verbose_name='Color ID')),
                ('category', models.ForeignKey(help_text='Pick a Category to help others find your Shortcut', null=True, on_delete=django.db.models.deletion.SET_NULL, to='share.Category')),
                ('tags', models.ManyToManyField(help_text='Tag your Shortcut to help others find it', to='share.Tag')),
            ],
        ),
    ]
