# Generated by Django 2.2.6 on 2019-11-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tag your Shortcut to help others find it', to='share.Tag'),
        ),
    ]
