# Generated by Django 2.2.6 on 2019-11-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20191110_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Pick a Category to help others find your Shortcut', null=True, on_delete=django.db.models.deletion.SET_NULL, to='share.Category'),
        ),
    ]
