# Generated by Django 2.2.6 on 2019-11-10 08:16

from django.db import migrations
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20191110_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='Actions',
            field=share.models.JSONField(verbose_name='Shortcut Actions'),
        ),
    ]
