# Generated by Django 2.2.6 on 2019-11-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20191110_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcut',
            old_name='Actions',
            new_name='actions',
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='download_link',
            field=models.URLField(max_length=600, verbose_name='Download Link'),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tag your Shortcut to help others find it', null=True, to='share.Tag'),
        ),
    ]
