# Generated by Django 2.2.6 on 2019-11-19 04:05

from django.db import migrations
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20191111_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='UUID_glyphs',
            field=share.models.JSONField(default={}, verbose_name='UUID Glyphs'),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='actions',
            field=share.models.JSONField(default={}, verbose_name='Shortcut Actions'),
        ),
    ]
