# Generated by Django 2.2.6 on 2019-11-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20191119_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcut',
            old_name='actions',
            new_name='actions_blocks',
        ),
    ]
