# Generated by Django 2.2.6 on 2019-11-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20191119_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='accepted_types',
            field=models.CharField(default='', max_length=1000, verbose_name='Accepts'),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='shortcut_types',
            field=models.CharField(default='', max_length=200, verbose_name='Shortcut Types'),
        ),
    ]
