# Generated by Django 2.2.7 on 2019-11-27 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_shortcut_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
    ]
