# Generated by Django 2.2.7 on 2019-11-29 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0011_shortcut_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', related_query_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved', related_query_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
