# Generated by Django 2.2.7 on 2019-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0013_auto_20191212_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tag your Shortcut to help others find it', to='share.Tag'),
        ),
    ]
